pickup_points = [
                ["Saurashtra University", "BT Savani (Kidney) Hospital", "Akashvani Chowk", "Panchayat Nagar Chowk", "Indira Circle", "Indubai Mahasatiji Chowk", "Swaminarayan Mandir / Mahila College Chowk", "Astron Chowk", "Hemu Gadhvi Hall", "Ramkrushna Ashram", "Malaviya Chowk", "Trikon Baug"],  # 1
            
                ["H N Shukla College", "Pradyuman Park", "Marketing Yard", "Bhagirath Society", "Lakheshwar Society - R.T.O Office", "Gram Udyog Mandir Pedak", "Satellite Chowk - Maruti Nagar Approach Chowk", "Ayak Nagar - Pedak Chowk", "Narayan Nagar Approach Road", "Champak Nagar - Panino Ghodo", "Patel Vadi", "Parevadi Chowk", "Hospital Chowk", "Jubilee Baug", "Trikon Baug", "Malaviya Chowk", "Ramkrushna Ashram", "Dharmendrasinhji College", "Jilla Panchayat Chowk", "Kisanpara Chowk", "Swaminarayan Chowk", "Indubhai Mahasatiji Chowk", "Indira Circle", "Panchayat Nagar Chowk", "Jivan Jyot School", "Sadhu Vaswani School", "Ajanta Park / Janakpuri", "Balaji Park / Satellite Park", "Aalap Green City", "Raiya Gam"],  # 2
            
                ["Jivraj Park", "Aarya Land Residency", "Jetco Chokdi", "Dream City", "Mavdi Gam", "Mavdi Chowk", "Fuliya Hanuman Mandir", "Mavdi Fire Station", "Anand Banglow", "Swaminarayan Chowk", "P.D.M College", "Gurukul", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "S.T Bus Stand", "Trikon Baug", "Jubilee Baug", "Hospital Chowk", "I.P Mission", "Kothi Compound", "Junction Railway Station", "Popatpara Central Jail", "Popatpara", "Central Warehouse", "Bhaktinagar Park"],  # 3
            
                ["Jubilee Baug", "Trikon Baug", "Malaviya Chowk", "Ramkrushna Ashram", "Hemu Gadhvi Hall", "Astron Chowk", "Swaminarayan Mandir / Mahila College Chowk", "Indubai Mahasatiji Chowk", "K.K.V Hall", "Atmiya University", "Crystal Mall", "Vrundavan Society", "A.G Chowk", "Everest Park", "Mota Mauva", "Kankot Kalawad Road", "Vruksh Mandir", "Uma P.T.C College", "Mukhyamantri Awas Yojna Quarter", "Haripar Gam", "V.V.P Engineering College", "Virda Vajadi Gam", "Vagudad", "Vad Vajadi", "G.I.D.C. Gate 1", "G.I.D.C. Gate 2", "G.I.D.C. Gate 3"],  # 4
            
                ["Raiya Village", "Aalap Green City", "Bapa Sitaram Chowk", "Raiya Chowk", "Brahmasamaj Chowk", "Hanuman Madhi", "Alkapuri", "Azad Chowk", "Amrapali Fatak", "Kisanpara Chowk", "Jilla Panchayat Chowk", "Fulchhab Chowk", "Chitralekha Chowk", "Limda Chowk", "Trikon Baug", "S.T Bus Stand", "Arya Samaj", "Kanta Stri Vikas Gruh", "Bhaktinagar Circle", "Sheth High School", "Kothariya Colony", "Sorathiyavadi Circle", "Jangleshwar Crossing / Bapunagar", "Satyam Park", "Aji G.I.D.C.", "Field Marshal Chowk", "Government Polytechnic", "Aji Dam", "Mansarovar Society", "Aarti Industrial Area", "Thebachda - Mahika Pattiu", "Krishna International School", "Kalipat", "R.K. University", "Bharad Engineering College", "Tramba Village"],  # 5
            
                ["Santoshinagar Railway Crossing", "Santoshinagar", "Railnagar", "Central Warehouse", "Popatpara", "Popatpara Central Jail", "Junction Railway Station", "Kothi Compound", "I.P Mission", "Hospital Chowk", "Jubilee Baug", "Trikon Baug", "S.T Bus Stand", "Arya Samaj", "Kadvibai School", "Bhaktinagar Circle", "Sheth High School", "Kothariya Colony", "Sorathiyavadi Circle", "Jangleshwar Crossing / Bapunagar", "Satyam Park", "Aji G.I.D.C.", "Field Marshal Chowk", "Government Polytechnic", "Aji Dam", "Mansarovar Society", "Aarti Industrial Area", "Thebachda - Mahika Pattiu", "Krishna International School", "Kalipat", "R.K. University", "Bharad Engineering College", "Tramba Village"],  # 6
            
                ["Bajrangvadi Circle", "Punitnagar", "Lakhno Banglow", "Ramapir Chokdi", "Nanavati Chowk", "Raiya Chowkdi", "Brahmasamaj", "Hanuman Madhi", "Alkapuri", "Azad Chowk", "Amrapali Fatak", "Kisanpara Chowk", "Jilla Panchayat Chowk", "Fulchhab Chowk", "Chitralekha Chowk", "Limda Chowk", "Trikon Baug", "S.T. Bus Stand", "Arya Samaj", "Kanta Stri Vikas Gruh", "Bhaktinagar Circle"],  # 7
            
                ["Greenland Chowkdi", "Marutinagar 50 Feet Road Chowk", "Gurudev Park", "Ranchhod Ashram", "Parevadi Chowk", "I.P Mission School", "Hospital Chowk", "Jubilee Baug", "Trikon Baug", "S.T Bus", "Arya Samaj", "Kadvibai School", "Makkam Chowk", "Anand Banglows", "Mavdi Fire Station", "Fuliya Hanuman Mandir", "Mavdi Chowk", "Bapa Sitaram Chowk", "Mavdi Gam", "Dream City", "Jetco Chokdi", "Government Engineering College", "Labhubhai Trivedi Engineering College"],  # 8

                ["Arpit Engineering College", "Darshan Engineering College", "Ratanpar (Ramji Mandir)", "Ratanpar Gam", "Ratanpar Telephone Exchange", "Gauridal", "I.O.C.", "Marwadi College", "Bedi Marketing Yard", "Bedi", "150 Feet Jamnagar Road Crossing", "Mukhyamantri Aavas Yojna Quarter", "Astha Sanghrila", "Krishna Banglows 3", "Manharpura", "Madhapar Chowk", "Vora Society", "Gaytridham", "Vankaner Society", "Bajarang Vadi", "Railway Colony", "Bhomeshwar", "Special School For Boys", "Ruda Office", "Hospital Chowk", "Jubilee Baug", "Trikon Baug", "Malaviya Chowk", "Ramkrushna Ashram", "Jilla Panchayat Chowk", "Kishanpara Chowk", "Indubai Mahasatiji Chowk", "K.K.V. Hall", "Crystal Mall", "A.G. Society", "Sarita Vihar", "Saurashtra University"], #9

                ["-"], #10

                ["Shapar Veraval", "Maruti Nagar", "Shitalamataji Nu Mandir", "Pardi Gam", "Aastha Green City", "Khokhadadad", "A.V. Jasani T.B. Hospital", "Kothariya Solvent", "Gondal Chowkdi", "P and T Colony / Gitanagar", "S.T. Workshop", "Panchshil Society", "Rajshri Auto", "P.D.M. College", "Makkam Chowk", "Bombay Hotel", "S.T. Bus Stand", "Trikon Baug"], #11

                ["-"], #12

                ["Kothariya Chowkdi", "Hudko Police Chowkdi", "Govind Nagar", "Ghanshyam Nagar / Nanda Hall", "Devpara", "Nilkanth Cinema", "50 Feet Road Crossing", "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "Arya Samaj", "S.T. Bus Stand", "Trikon Baug", "Jubilee Baug", "Hospital Chowk", "I.P. Mission School", "Kothi Compound", "Junction Railway Station", "Popatpara Chowk", "Popatpara", "Central Ware House", "Railnagar", "Santoshi Nagar"], #13

                ["Kothariya Gam", "Ranuja Temple", "Gokul Park", "Kothariya Chowk", "Hudco Police Chowki", "Ghanshyam Nagar / Nanda Hall", "Devpara", "Nilkanth Cinema", "50 Feet Road Crossing", "Sorathiyavadi Circle", "Kevadavadi", "Gundawadi Police Chowki", "Ashapura Temple", "Diwanpara Police Chowki", "Balaji Hanuman", "Trikon Baug", "Jubilee Baug", "Hospital Chowk", "I P Mission", "Parevadi Chowk", "Ranchhoddas Ashram", "Gurudev Park", "Shree Ram Park - Kuvadva", "Greenland Chokdi", "Kuvadva Police Chowki", "Navagam"], #14

                ["Kothariya Gam", "Ranuja Temple", "Gokul Park", "Kothariya Chowk", "Hudco Police Chowki", "Ghanshyam Nagar / Nanda Hall", "Devpara", "Nilkanth Cinema", "50 Feet Road Crossing",  "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle",  "Kanta Stri Vikas Gruh", "Aryasamaj", "S T Bus Stand", "Trikon Baug", "Malaviya Chowk",  "Ramkrushna Ashram", "Hemu Gadhvi Hall", "Astron Chowk", "Mahila College Chowk",  "Swaminarayan Mandir", "Kotecha Chowk", "Wockhardt Hospital", "K K V Hall",  "Atmiya College / Central School", "Crystal Mall", "Vrundavan Society", "A G Society",  "Everest Park", "Mota Mauva", "Rangoli Park / Lakshmino Dholo", "Cosmoplex Cinema",  "Kankot - Kalawad Road", "Vrukshmandir", "Uma P.T.C. College", "Haripar Village",  "V.V.P. Engineering College", "Virda Vajadi Village", "Vagudad Village", "Vadvajadi Village",  "G.I.D.C. Gate 1", "G.I.D.C. Gate 2", "G.I.D.C. Gate 3"], #15

                ["Kothariya Gam", "Ranuja Temple", "Gokul Park", "Kothariya Chowk", "Hudco Police Chowki", "Ghanshyam Nagar / Nanda Hall", "Devpara", "Nilkanth Cinema", "50 Feet Road Crossing",  "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle",  "Kanta Stri Vikas Gruh", "Aryasamaj", "S T Bus Stand", "Trikon Baug", "Limda Chowk",  "Chitralekha Chowk", "Fullchhab Chowk", "Jilla Panchayat Chowk", "Kisanpara Chowk",  "Mahila College Chowk", "Kotecha Chowk", "Wockhardt Hospital", "K K V Hall",  "Atmiya College / Central School", "Crystal Mall", "Vrundavan Society", "A G Society",  "Rular Housing", "Pushkardham", "B. T. Savani (Kidney) Hospital", "Saurashtra University"], #16

                ["Saurashtra University", "B. T. Savani (Kidney) Hospital", "Shiv Shakti Colony", "Akashvani Chowk", "Jivan Jyot Chowk", "Ajit Bera , A/5, Janki Appartment, Panchayat Nagar Bus Stand", "Indira Circle", "Kotecha Chowk", "Swaminarayan Mandir", "Mahila College Chowk", "Astron Chowk", "Hemu Gadhvi Hall", "Ramkrushna Ashram", "Malaviya Chowk", "Trikon Baug", "S T Bus Stand", "Aryasamaj", "Kanta Stri Vikas Gruh", "Bhaktinagar Circle", "Sheth High School", "Kothariya Colony", "Sorathiyavadi Circle", "Jangleshwar Crossing / Bapunagar", "Satyam Park", "Aji G.I.D.C.", "Field Marshal Chowk", "Government Polytechnic", "Aji Dam", "Mansarovar Society", "Aarti Industrial Area", "Thebachda - Mahika Patiu", "Krishna International School", "Kalipat", "R.K. University", "Bharad Engineering College", "Tramba Village"], #17

                ["Aji Dam", "Government Polytechnic", "Field Marshal Chowk", "Aji G.I.D.C.", "Satyam Park", "Jangleshwar Crossing / Bapunagar", "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "Aryasamaj", "S T Bus Stand", "Trikon Baug", "Malaviya Chowk", "Ramkrushna Ashram", "Dharmendrasinhji College", "Jilla Panchayat Chowk", "Kisanpara Chowk", "Swaminarayan Mandir", "Kotecha Chowk", "Wockhardt Hospital", "K K V Hall", "Atmiya College/Central School", "Crystal Mall", "Vrundavan Society", "A G Society", "Everest Park", "Mota Mauva", "Rangoli Park/Lakshmino Dholo", "Cosmoplex Cinema", "Kankot - Kalawad Road", "Vrukshmandir", "Uma P.T.C. College", "Haripar Village", "V.V.P. Engineering College", "Virda Vajadi Village", "Vagudad Village", "Vadvajadi Village", "G.I.D.C. Gate 1", "G.I.D.C. Gate 2", "G.I.D.C. Gate 3"], #18

                ["Vavdee Village/school", "Vavdee Village/ward office", "Gautam budha nagar", "Punitnagar", "Punit Nagar BRTS", "Rajkamal Petrol Pump", "Gondal Chokdi", "P&T Colony/Gitanagar", "S.T.Workshop", "Panchsheel Society", "Shivnagar Doshi Hospital", "P.D.M. College", "Makkam Chowk", "Bombay Hotel", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "IP Mission", "Kothi compound", "Junction Railway Station", "Hansarajnagar", "Rafuji Colony/Shashtri Nagar", "Julelal Temple", "131 Slum Quater"], #19

                ["Ghanteshvar S.R.P. Camp", "Astha Residency", "Ghanteshvar Village", "Ghanteshvar Park", "Sainik Society", "Shethnagar", "Madhapar Village", "Madhapar Chowk", "Vora Society", "Gayatridham", "Wankaner society", "Bajarangavadi", "Railway Colony", "Bhomeshvar", "Special School For Boys", "Ruda Office", "Hospital Chowk", "Jubilee Baug", "Trikonbaug", "ST Bus Stand", "Aryasamaj", "Kadvibai School", "Makkam Chowk", "P.D.M. College", "Shivnagar - Doshi Hospital", "Panchsheel Society", "S.T.Workshop", "P&T Colony/Gitanagar", "Gondal Chokdi", "AV. Jasani T.B. Hospital", "Kothariya Solvent", "Khokhaldad", "Astha Green City", "Pardi Village", "Shitalamajaji Temple", "Marutinagar (Sarvoday Housing Society)", "Shapar Veraval", "Veraval (Shapar) Bus Stand"], #20

                ["Vidhyutnagar", "Rameshwari Chowk", "Santiniketan Park", "Shree Dharmeshwar Marg Chowk", "Nanavati Chowk", "Raiya Chowk", "Brahmasamaj Chowk", "Hanuman Madhi", "Sichay nagar-hanuman madhi", "Sankalp Siddh Park", "Geet gunjari crosing", "Police Head Quarter", "Bahumalibhavan", "Shardabag", "Chodhari high shcool", "Jubilee Baug", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "IP Mission", "Parevadi Chowk", "Patel Vadi", "Champak nagar - Panino Ghodo", "Narayan nagar aproch road govind nagar", "Aryanagar Pedak road", "Satellite Chowk - Marutinagar aproach Road", "Gramudhyog Mandir Pedak", "Lakheshwar Society - R.T.O. Office", "Bhagirath Society - Marketing Yard", "Marketing Yard"], #21

                ["H & N Shukla College", "JK Park", "Gajanand Chowk", "Amrut Park Main Road", "Kailashdhara Park", "Vidhyutnagar", "Rameshwari Chowk", "Santiniketan Park", "Shree Dharmeshwar Marg Chowk", "Nanavati Chowk", "Raiya Chowk", "Brahmasamaj Chowk", "Hanuman Madhi", "Alkapuri", "Azad Chowk", "Amrapali Fatak", "Kisanpara Chowk", "Jilla Panchayat Chowk", "Fullchhab Chowk", "Chitralekha Chowk", "Limda Chowk", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "I P Mission", "Parevadi Chowk", "Patel Vadi", "Champak nagar - Panino Ghodo", "Narayan nagar aproch road govind nagar", "Aryanagar - Pedak road", "Satellite Chowk - Marutinagar aproach Road", "Gramudhyog Mandir Pedak", "Lakheshwar Society - R.T.O. Office", "Bhagirath Society - Marketing Yard", "Marketing Yard", "Pradhyuman Park", "H & N shukla College"], #22

                ["Mavdi Village", "Akshar Complex", "Jai Sardar Chowk", "Shyamal City", "Gurudev Park 2", "Sanskar City", "Radha Krishna Chowk", "Sorathiya Parivar vadi", "Bapa Sitaram Chowk", "Mavdi Chowk", "Fuliya Hanuman Temple", "Mavdi Fire Station", "Mayani chowk", "Madhunagar/Rajnagar Society", "Suryamukhi Hanuman Chowk", "Chandreshvadi Chowk", "Gautam Nagar", "Amin Road Akshar Road Crossing", "Mahila College Chowk", "Kisanpara Chowk", "Jilla Panchayat Chowk", "Fullchhab Chowk", "Chitralekha Chowk", "Limda Chowk", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "IP Mission", "Parevadi Chowk", "Patel Vadi", "Jalaram Chowk-Santkabir Road Comer", "Sardar Vallabhbhai Vidhyalay", "Govind Baug", "Gadhiyanagar", "Dudheshvar Mahadev", "Marketing Yard", "Pradhyuman Park"], #23

                ["G.I.D.C. Gate 3", "G.I.D.C. Gate 1", "Vadvajdi Village 2", "Vadvajdi Village", "Vagudad Village", "Virda Vajdi Village", "V.V.P. Engineering College", "Haripar Village", "Uma P.T.C. College", "Vruksh Mandir", "Kankot - Kalawad Road", "Cosmoplex Cinema", "Rangoli Park / Lakshmi No Dholo", "Mota Mauva", "Everest Park", "A.G. Society", "Vrundavan Society", "Crystal Mall", "Atmiya College / Central School", "K.K.V. Hall", "Wockhardt Hospital", "Kotecha Chowk", "Mahila College Chowk", "Kishanpara Chowk", "Jilla Panchayat Chowk", "Dharmendrasinhji College", "Jagnath Mandir", "Ramkrushna Ashram", "Malaviya Chowk", "Trikon Baug"], #24

                ["131 Slum Quater", "Rafuji Colony/Shashtri Nagar", "Hansarajnagar", "Junction Railway Station", "Kothi Compound", "I P Mission", "Hospital Chowk", "Jubilee Baug", "Trikonbaug", "Malaviya Chowk", "Ramkrushna Ashram", "Hemu Gadhvi Hall", "Astron Chowk", "Amin Road Akshar Road Crossing", "Amin Road Civic Center", "Hinglajnagar (Bharvad Chowk)", "Astron Society", "Suryamukhi Hanuman Chowk", "Grand Central Mall", "Nana Mava Chowk", "Satyasai Road Crossing", "Sastrinagar", "Alay Park", "Vrundavan Road Crossing", "Om Residency (Govani Hostel)", "Govani Hostel", "Ambika Township", "Jivraj Park"], #25

                ["Vavdee Village/school", "Vavdee Village/ ward office", "Gautam budha nagar", "Punitnagar", "Jograna Chowk", "Dr. Ambedakar Chok", "Gokul approch(Nirav Complex)", "Gokuldham", "Panchashil Soc. Approch Road", "Guruprasad Chowk", "Swaminarayan Chowk", "Ambaji Kadva Plot", "P.D.M. College", "Jasani School", "Gopalnagar Choro", "Gurukul", "Kadvibai School", "Aryasamaj", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "IP Mission", "Kothi compound", "Junction Railway Station", "Junction Railway police station", "Popatpara Central Jail", "53 Quater/Popat para", "Ghanshyam Residency", "Amrut Residency - 2", "Santoshinagar"], #26

                ["Trikonbaug", "Limda Chowk", "Chitralekha Chowk", "Fullchhab Chowk", "Jilla Panchayat Chowk", "Kisanpara Chowk", "Amrapali Fatak", "Azad Chowk", "Alkapuri", "Hanuman Madhi", "Brahmasamaj Chowk", "Raiya Chowk", "Nanavati Chowk", "Ramdevpir Chowk", "Svapnalok Resi.", "Shree Ranima rudima chok", "Shantinagar", "Raiyadhar Slum Quarter"], #27

                ["Gujarat Housing Board Quarter/Sagar Chok", "Insurance (vima) Hospital", "Rajkot Dairy", "Chunaravad Chowk", "Ramnath Para (B-Division Police Station)", "Jilla Garden Chowk", "Gundawadi Police Chowki", "ST Bus Stand", "Trikonbaug", "Malaviya Chowk", "Ramkrushna Ashram", "Hemu Gadhvi Hall", "Astron Chowk", "Mahila College Chowk", "Swaminarayan Mandir", "Kotecha Chowk", "Wockhardt Hospital", "KKV Hall", "Atmiya College/Central School", "Swati Soc.", "Satysai Hospital", "Alap Heritage", "Phulvadi Park", "Satysai Road Crossing", "Sastrinagar", "Alay Park", "Vrundavan Road Crossing", "Om Residency (Govani Hostel)", "Govani Hostel", "Ambika Township", "Jivraj Park"], #28

                ["-"], #29

                ["Trikon Baug", "S.T. Bus Stand", "Aaryasamaj", "Kanta Stri Vikash Gruh", "Bhaktinagar Circle", "Jalaram Chowk", "Jivraj Hospital", "Trishul Chowk", "Babariya Colony", "Aahir Chowk", "Shyam Hall", "Patel Chowk", "New Subhashnagar", "Ghanshyam Nagar/Nanda Hall", "Raghuvansi Society", "Pipaliya Hall/Bhakti Hall", "Valkeshwar", "Jaljit Hall", "Sheth High School"], #30

                ["Trikonbaug", "ST Bus Stand", "Kanta Stri Vikas Gruh", "Bhaktinagar Circle", "Sheth High School", "Jalit Hall", "Valkeshwar Society", "Pipaliya Hall/Bhakti Hall", "Sahakar Society", "Ghanshyam Nagar/Nanca Hall", "New Subhashnagar", "Patel Chowk", "Shyam Hall", "Any Chowk", "Babariya Colony", "Pipaliya Hall/Bhakti Hall", "Trishul Chowk", "Jivraj Hospital", "Jaluram Chowk (Gayatrinagar Road)", "Bhaktinagar Circle", "Kadval School", "Aryasamaj", "ST Bus Stand", "Trikonbaug"], #31

                ["Tramba Village", "Bharad Engineering College", "R.K. University", "Kalipat", "Krishna International School", "Thebachda - Mahika Patiu", "Aarti Industrial Area", "Mansarovar Society", "Aji Dam", "Government Polytechnic", "Field marshal Chowk", "Aji G.I.D.C.", "Satyam Park", "Jangleshwar Crossing/Bapunagar", "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "Aryasamaj", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "Ruda Office", "Special School For Boys", "Parsananagar (Ayapapaa mandir)", "Parsana Nagar"], #32

                ["Ashapura mandir", "mahika patiyu", "thebchada-mahika patiyu", "aarti industrial area", "mansarovar society", "ajidam chokdi", "government polytechnic", "Field marshal Chowk", "Aji G.I.D.C.", "Satyam Park", "Jangleshwar Crossing/Bapunagar", "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "Ruda Office", "Special School For Boys", "Parsananagar (Ayapapaa mandir)", "Parsana Nagar main road", "Parsana Nagar"], #33

                ["Marketing Yard", "Dudheshwar Mahadev", "Gadhiya Nagar", "Govind Baug", "Sardar Vallabhbhai Vidyalay", "Jalaram Chowk", "Patel Vadi", "Parevadi Chowk", "I.P. Mission School", "Hospital Chowk", "Jubilee Baug", "Malaviya Chowk", "Ramkrushna Ashram", "Dharmendrasinhji College", "Jilla Panchayat Chowk", "Kishanpara Chowk", "Swaminarayan Mandir", "Kotecha Chowk", "Indira Circle", "Ajit Bera, A/5, Janki Apartment, Panchayat Nagar Bus Stand", "Jivan Jyot Chowk", "Akashvani Chowk", "Pushkardham", "Vimal Nagar", "A.G. Staff Quarter", "Prasheel Park", "Saurashtra University", "Shree City", "Munjaka Gam", "Christ College"], #34

                ["Trikonbaug", "ST Bus Stand", "Aryasamaj", "Kadvibai School", "Gurukul", "Gopalnagar Choro", "Jasani School", "P.D.M. College", "Shivnagar - Doshi Hospital", "Panchsheel Society", "S.T.Workshop", "P&T Colony/Gitanagar", "Rajkamal Petrol Pump", "Gondal Chokdi", "Kothariya Solvent", "A V Jasani TB Hospital", "Khokhaldad", "Astha Green City", "Pardi Village", "Shitalamajaji Temple", "Marutinagar (Sarvoday Housing Society)", "Shapar Veraval", "Veraval (Shapar) Bus Stand"], #35

                ["Bhaktinagar Circle", "Kanta Sri Vikas Gruh", "Aryasamaj", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "Ruda Office", "Special School For Boys", "Bhomeshvar", "Railway Colony", "BajrangWadi circle", "Wankaner Socity Corner", "Wankaner society", "Gayatridham", "Vora Society", "Madhapar Chowk", "Madhapar Village", "Shethnagar", "Sainik Society", "Nageshavar jain Derashar", "Unicare Hospital", "Ghanteshvar Park", "Ghanteshvar Village", "Ghantshwar SRP Camp Road Crossing", "Parapipaliya Village", "Ekta Society", "Nyara Village Chokdi"], #36

                ["Vinod Nagar", "Santoshinagar Railway Crossing", "Satya Prakash School", "Pardi Road crossing", "New Lalbahadur Society (Pardi Chowk)", "Lalpark Chowk", "Ahir Chowk", "Babariya Colony", "Pipaliya Hall/Bhakti Hall", "Trishul Chowk", "Jasani School", "Gopalnagar Choro", "Gurukul", "Kadvibai School", "Aryasamaj", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "IP Mission", "Kothi compound", "Junction Railway Station", "Popatpara Central Jail", "Popatpara", "Central Ware House", "Railnagar", "Santoshinagar", "Lokmany Tilak/Subhas chandra bose avash", "Virsavarkar Avash (Bharat Petrol Pump)", "Maharshi Arvind Avash", "Chatrapati Shivaji Township"], #37

                ["Aji Dam", "Government Polytechnic", "Field marshal Chowk", "Aji G.I.D.C.", "Satyam Park", "Jangleshwar Crossing/Bapunagar", "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "Aryasamaj", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "Ruda Office", "Special School For Boys", "Bhomeshvar", "Railway Colony", "Bajrangavadi", "Bajrang Wadi circle", "Wankaner Socity Corner", "Wankaner society", "Gayatridham", "Vora Society", "Madhapar Chowk", "Madhapar Bus Stand (GSRTC)"], #38

                ["-"], #39

                ["Saurastra University Bus Stop", "Saurastra University", "Saurastra University Gate", "B. T. Savani (Kidney) Hospital", "Shiv Shakti Colony", "Akashvani Chowk", "Jivan Jyot Chowk", "Ajit Bera, A/5, Janki Appartment, Panchayat Nagar Bus Stand", "Indira Circle", "SBI Bank Chowk", "Kotecha Chowk", "Swaminarayan Mandir", "Kisanpara Chowk", "Jilla Panchayat Chowk", "Bahumalibhavan", "Shardabag", "G.T.Sheth Hospital/Collector Office", "Jamtower Chowk", "Gebanshah Pir Dargah", "Junction Railway Station", "Junction Railway police station", "Popatpara Central Jail", "Popatpara", "Central Ware House", "Ashtha resi/Sadhuvasvani kunj road", "Railnagar", "Radhe Park", "Santoshinagar"], #40

                ["Vinod Nagar", "Satya Prakash School", "New Lalbahadur Society (Pardi Chowk)", "Lalpark Chowk", "Ahir Chowk", "Babariya Colony", "Pipaliya Hall/Bhakti Hall", "Trishul Chowk", "Jivraj Hospital", "Jalaram Chowk (Gayatrinagar Road)", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "Aryasamaj", "ST Bus Stand", "Trikonbaug", "Malaviya Chowk", "Ramkrushna Ashram", "Hemu Gadhvi Hall", "Astron Chowk", "Mahila College Chowk", "Swaminarayan Mandir", "Kotecha Chowk", "SBI Bank Chowk", "Jalaram Plot", "Africa Colony", "Raiya Telephone Excenge", "Golden Park", "Tulsi Baag", "Jay Gopal Chowk", "Balaji Park/Satellite Park", "Patidar Chowk", "Radhe Park/Gangotri Park"], #41

                ["Greenland chokdi Pickup Stand (GSRTC)", "Greenland Chokdi", "Marutinagar 50ft Road Chowk", "Gurudev Park", "Ranchhoddas Ashram", "Parevadi Chowk", "IP Mission", "Hospital Chowk", "Jubilee Baug", "Trikonbaug", "Malaviya Chowk", "Ramkrushna Ashram", "Dharmendrasinhji College", "Jagnath Mandir", "Jilla Panchayat Chowk", "Kisanpara Chowk", "Mahila College Chowk", "Kotecha Chowk", "Wockhardt Hospital", "KKV Hall", "Atmiya College/Central School", "Crystal Mall", "Vrundavan Society", "Rajkot Mahanagar Palika Aavas", "Vrundavan Road Crossing", "Bheemarav Nagar/Om Residency", "Govani Hostel", "Ambika Township", "Jivraj Park", "Mota Mava"], #42

                ["Om Residency", "Bhagavatipara (Jay Prakashnagar)", "Jay Prakashnagar Society", "BhagavatiPara Police Choki", "Mahakali Society", "BhagavatiPara Sheri No. 9", "Trikon Baug", "S.T. Bus Stand", "Bombay Hotel", "Bhaktinagar Station", "Makkam Chowk", "Svashray Society", "Aanand Bunglows", "Ashok Garden", "Pandit Dindayal", "Rajnagar Main Road Crossing", "Chandranagar Shakmarket", "Vishvanagar", "Sanidhya Bunglows", "Mahapuja Dham", "Omnagar", "Shree Sahjanand Dham", "Yadunandan Chowk", "New Rajdeep Society", "Akshar Vatika (Mavdi)"], #43

                ["Trikonbaug", "ST Bus Stand", "Aryasamaj", "Kanta Stri Vikas Gruh", "Bhaktinagar Circle", "Sheth High School", "Kothariya Colony", "Sorathiyavadi Circle", "Jangleshwar Crossing/Bapunagar", "Satyam Park", "Aji G.I.D.C.", "Field marshal Chowk", "Government Polytechnic", "Aji Dam", "Mansarovar Society", "Aarti Industrial Area", "Thebachda - Mahika Patiu", "Krishna International School", "Kalipat", "R.K. University", "Bharad Engineering College", "Tramba Village"], #44

                ["Saurastra University Bus Stop", "Saurastra University", "Saurastra University Gate", "B. T. Savani (Kidney) Hospital", "Shiv Shakti Colony", "Akashvani Chowk", "Jivan Jyot Chowk", "Ajit Bera, A/5, Janki Appartment, Panchayat Nagar Bus Stand", "Indira Circle", "SBI Bank Chowk", "Kotecha Chowk", "Swaminarayan Mandir", "Mahila College Chowk", "Astron Chowk", "Hemu Gadhvi Hall", "Ramkrushna Ashram", "Malaviya Chowk", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "IP Mission", "Parevadi Chowk", "Ranchhoddas Ashram", "Gurudev Park", "Shree Ram Park - Kuvadva", "Greenland Chokdi", "Shiv Jhara Residency", "Jai Jawan Jai Kisan Society", "Indraprasth Society", "Velnathpara Beginning (Nr. School No. 71)", "Velnathpara (Street No. 17)", "150 Feet Ring Road - Morbi Road Crossing", "Bedi", "Marvadi college", "I.O.C.", "Gauridad", "Ratanpar telephone exechange", "Ratanpar Village", "Ratanpar (ramji mandir)"], #45

                ["Arpit Eng. College (Hadala Gam)", "Darshan Eng. College", "Ratanpar (Ramji Mandir)", "Ratanpar gam", "Ratanpar Telephone Exchange", "Gavridad", "I.O.C.", "Marwadi College", "Bedi Marketing Yard", "150 Feet Jamnagar Road Crossing", "Velnathpara (Sheri No. 17)", "Velnathpara Saruaat (Shala No. 71 Paase)", "Indraprasth Society", "Jay Jawan Jay Kishan Society", "Shivdhara Residency", "Greenland Chokdi", "Marutinagar 50 Feet Road Chowk", "Ranchhod Aashram", "Parevadi Chowk", "Hospital Chowk", "Jubilee Baug", "Trikon Baug"], #46

                ["Kothariya Village", "Kothariya Housing", "Ranuja Temple", "Gokulpark", "Kothariya Chowk", "Hudco Police Chowki", "Govind Nagar", "Ghanshyam Nagar/Nanda Hall", "Devpara", "Nilkanth Cinema", "50 Feet Road Crossing", "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle", "Makkam Chowk", "Bhaktinagar Station", "Hemu Gadhvi Hall", "Astron Chowk", "LIC Office", "Swaminarayan Mandir", "Kotecha Chowk", "SBI Bank Chowk", "Indira Circle", "Ajit Bera, A/5, Janki Appartment, Panchayat Nagar Bus Stand", "Jivan Jyot Chowk", "Akashvani Chowk", "Shiv Shakti Colony", "B. T. Savani (Kidney) Hospital", "Saurastra University Gate", "Saurastra University", "Saurastra University Bus Stop"], #47

                ["-"], #48

                ["-"], #49

                ["-"], #50

                ["Ghanteshvar S.R.P. Camp", "Astha Residency", "Ghanteshvar Village", "Ghanteshvar Park", "Sainik Society", "Shethnagar", "Madhapar Village", "Madhapar Chowk", "Vora Society", "Gayatridham", "Wankaner society", "Bajarangavadi", "Railway Colony", "Bhomeshvar", "Jagruti Shramjivi Society", "Bhomeshvar", "Special School For Boys", "Ruda Office", "Hospital Chowk", "Jubilee Baug", "Trikonbaug", "ST Bus Stand", "Aryasamaj", "Kadvibai School", "Makkam Chowk", "Anand Bunglow Chowk", "Sarojeeni Nayadu School (Ambaji Kadva Plot)", "Swaminarayan Chowk", "Guruprasad Chowk", "Panchashil Soc. Approch Road", "Gokuldham", "Gokul approch(Nirav Complex)", "Dr. Aambedakar Chok", "Jograna Chowk", "Punit Nagar"], #51

                ["-"], #52

                ["-"], #53

                ["Kothariya Chowk", "Hudco Police Chowki", "Ghanshyam Nagar/Nanda Hall", "Devpara", "Nilkanth Cinema", "50 Feet Road Crossing", "Sorathiyavadi Circle", "Kothariya Colony", "Sheth High School", "Bhaktinagar Circle", "Kanta Stri Vikas Gruh", "Aryasamaj", "ST Bus Stand", "Trikonbaug", "Jubilee Baug", "Hospital Chowk", "Ruda Office", "Special School For Boys", "Bhomeshvar", "Jagruti Shramjivi Society", "Bhomeshvar", "Railway Colony", "Bajarangavadi", "BajrangWadi circle", "Wankaner Socity Corner", "Wankaner society", "Gayatridham", "Vora Society", "Madhapar Chowk", "Madhapar Village", "Shethnagar", "Sainik Society", "Ghanteshvar Park", "Ghanteshvar Village", "Astha Residency", "Ghanteshvar S.R.P. Camp"], #54

                ["-"], #55

                ["Trikon Baug", "Malaviya Chowk", "Ramkrushna Ashram", "Hemu Gadhvi Hall", "Astron Chowk", "Mahila College Chowk", "Swaminarayan Mandir", "Kotecha Chowk (22.290491,70.7784)", "Wockhardt Hospital", "KKV Hall", "Atmiya College/Central School", "Crystal Mall", "Vrundavan Society", "A G Society", "Everest Park", "Mota Mauva", "Rangoli Park/Lakshmino Dholo", "Sunshine Group of Institute", "Labhubhai Engineering College", "Government Engineering College"], #56

                ["Trikon Baug", "Malaviya Chowk", "Ramkrushna Ashram", "Hemu Gadhavi Hall", "Astron Chowk", "Swaminarayan Mandir / Mahila College Chowk", "Indubai Mahasatiji Chowk", "K.K.V. Hall", "Atmiya College / Central School", "Crystal Mall", "A.G. Society", "Everest Park", "Mota Mauva", "Cosmoplex Cinema", "Kankot Patiya", "Labhubhai Engineering College", "Government Engineering College"] #57
                 ]


source = input("Enter Pickup Point: ")
destination = input("Enter Destination Point: ")

print("You can go in follorwing buses: ")
for i in range(len(pickup_points)):
    if source in pickup_points[i] and destination in pickup_points[i]:
        print(f"R{i + 1}")